import json
from pathlib import Path

caso = {
  "expediente": "2142-2026/CC1",
  "denunciante": "EFRAÍN CORONEL QUISPE",
  "denunciado": "LA POSITIVA SEGUROS Y REASEGUROS S.A.A. (LA POSITIVA)",
  "fecha_res": "Lima, 20 de julio de 2026",
  "fecha_denuncia": "20 de abril de 2026__F1__",
  "intro_denuncia": "el señor Efraín Coronel Quispe denunció a La Positiva por presuntas infracciones a la Ley 29571, Código de Protección y Defensa del Consumidor (en adelante, Código)__F2__,",
  "hechos": [
    "El 6 de julio de 2023, el señor Efraín Coronel Quispe (en adelante, el denunciante) contrató un seguro vehicular con La Positiva Seguros y Reaseguros S.A.A. (en adelante, La Positiva), respecto del vehículo de placa BVO-787.",
    "El 22 de mayo de 2024, el vehículo asegurado fue objeto de robo total, tras lo cual se solicitó la cobertura respectiva.",
    "Sin embargo, La Positiva rechazó la cobertura del siniestro, sustentando su decisión en una supuesta utilización del vehículo en forma de alquiler.",
    "Asimismo, el denunciante señaló que la póliza tenía una vigencia hasta julio de 2024; no obstante, La Positiva habría renovado el seguro y continuado realizando cobros a su tarjeta CMR por un periodo adicional hasta julio de 2025, pese a tener conocimiento del robo del vehículo."
  ],
  "medida_correctiva": "El denunciante solicitó, en calidad de medida correctiva, que La Positiva cumpla con: (i) otorgar la cobertura del seguro vehicular por el siniestro de robo total; (ii) disponer el pago de la suma asegurada conforme a la póliza (USD 12 450,00); y, (iii) la devolución de los cobros indebidos. Asimismo, requirió de manera expresa el reembolso de costas y costos del presente procedimiento.",
  "imputaciones_analisis": [
    "La Secretaría Técnica de la Comisión de Protección al Consumidor 1 (en adelante, la Secretaría Técnica), en ejercicio de sus facultades__F3__, considera que el hecho denunciado, consistente en que La Positiva Seguros y Reaseguros S.A.A. habría negado al denunciante la cobertura del Seguro Vehicular por el siniestro del 22 de mayo de 2024; involucraría una presunta afectación a sus expectativas, quien no habría encontrado una correspondencia entre lo que esperaba recibir de parte del proveedor y lo que realmente recibió. Por consiguiente, corresponde calificar el hecho materia de denuncia como una presunta infracción al deber de idoneidad, tipificado en los artículos 18 y 19 del Código__F4__.",
    "Asimismo, la Secretaría Técnica, en ejercicio de sus facultades, considera que el hecho denunciado, consistente en que La Positiva Seguros y Reaseguros S.A.A. habría renovado el Seguro Vehicular y continuado realizando cobros en la tarjeta CMR del denunciante, pese a tener conocimiento de que el vehículo asegurado había sido robado. Por consiguiente, corresponde calificar el hecho materia de denuncia como una presunta infracción al deber de protección contra los métodos comerciales coercitivos, tipificado en el literal b) del artículo 56° del Código__F5__."
  ],
  "req_info": [
    "A efectos de tener mayores elementos que sirvan para la resolución definitiva del presente caso, la Secretaría Técnica, en ejercicio de las facultades que la ley le confiere, conviene requerir a la proveedora denunciada que, en un plazo no mayor de cinco (5) días hábiles contado a partir del día siguiente de la notificación de la presente resolución, cumpla con lo siguiente:",
    "A La Positiva: (i) presentar una copia debidamente suscrita de la Póliza de Seguro Vehicular materia de denuncia, que incluya las condiciones generales y particulares; (ii) presentar el pronunciamiento formal (carta de rechazo) respecto al siniestro del 22 de mayo de 2024; y, (iii) presentar los medios probatorios que acrediten la autorización del denunciante para la renovación de la póliza y los cobros efectuados en su tarjeta CMR posteriores a la fecha del siniestro."
  ],
  "imputaciones_res": [
    "Presunta infracción a los artículos 18° y 19° de la Ley N° 29571, Código de Protección y Defensa del Consumidor, en tanto La Positiva Seguros y Reaseguros S.A.A. habría negado al denunciante la cobertura del Seguro Vehicular por el siniestro del 22 de mayo de 2024.",
    "Presunta infracción al literal b) del artículo 56° de la Ley N° 29571, Código de Protección y Defensa del Consumidor, en tanto La Positiva Seguros y Reaseguros S.A.A. habría renovado el Seguro Vehicular y continuado realizando cobros en la tarjeta CMR del denunciante, pese a tener conocimiento de que el vehículo asegurado había sido robado."
  ],
  "notificaciones": [
    "poner en conocimiento de las partes que, antes de la emisión de la Resolución Final, tienen la posibilidad de formular su desistimiento o presentar el acuerdo arribado mediante la conciliación, mediación, transacción o cualquier otro que, de forma indubitable, deje constancia que se ha solucionado la controversia materia de denuncia.",
    "requerir al señor Efraín Coronel Quispe para que, dentro del plazo de dos (2) días hábiles siguientes a la fecha en que reciba la notificación en su bandeja de correo electrónico, efectúe la confirmación de recepción de la notificación remitida por este despacho a su correo electrónico veronikhalynch2024@gmail.com, de conformidad con el segundo párrafo del numeral 4 del artículo 20 del Texto Único Ordenado de la Ley del Procedimiento Administrativo General, aprobado mediante Decreto Supremo 006-2026-JUS, bajo apercibimiento de rehacer el acto de notificación y notificarle conforme al numeral 1 del artículo 20 del citado cuerpo normativo__F12__.",
    "requerir a La Positiva Seguros y Reaseguros S.A.A. para que efectúe el acuse de recibo mediante la confirmación de recepción de la notificación remitida por este despacho a su Casilla Electrónica, dentro de los cinco (5) primeros días hábiles siguientes a la fecha en que reciben la notificación."
  ],
  "resolutivos": {
    "PRIMERO": "admitir a trámite la denuncia del 20 de abril de 2026 interpuesta por el señor Efraín Coronel Quispe contra La Positiva Seguros y Reaseguros S.A.A., en atención a lo siguiente:",
    "SEGUNDO": "tener por ofrecidos los medios probatorios presentados en el escrito de denuncia del 20 de abril de 2026.",
    "TERCERO": "requerir a La Positiva Seguros y Reaseguros S.A.A. que cumpla con lo siguiente:\n(i)\tpresentar documentos que acrediten su inscripción en los Registros Públicos o una declaración jurada que indique que cuenta con dicha inscripción;\n(ii)\tpresentar copia simple de las facultades de representación de su representante legal en el presente procedimiento o la declaración jurada que indique que cuenta con dichas facultades y que estas se encuentran vigentes;\n(iii)\tconsignar el Número de Registro Único de Contribuyentes (RUC); y,\n(iv)\tfijar domicilio procesal para el procedimiento, de conformidad con el numeral 1 del artículo 442 del Código Procesal Civil. Para ello podrá señalar domicilio físico o una dirección electrónica a la que pueda remitirse las notificaciones;",
    "CUARTO": "correr traslado de la presente resolución a La Positiva Seguros y Reaseguros S.A.A. para que, de conformidad con lo dispuesto por el artículo 26° de la Ley sobre Facultades, Normas y Organización del Indecopi, aprobado por Decreto Legislativo N° 8079, presente sus descargos sobre la imputación de cargos realizada en un plazo no mayor a cinco (5) días hábiles contado a partir del día siguiente de la notificación de la presente resolución, vencido el cual, el Secretario Técnico declarará en rebeldía a los denunciados que no lo hubieran presentado. Debe precisarse que de conformidad con lo establecido por el artículo 223° del Texto Único Ordenado de la Ley N° 27444, Ley del Procedimiento Administrativo General, las alegaciones y los hechos relevantes de la reclamación, salvo que hayan sido específicamente negadas en la contestación, se tendrán por aceptadas o meritadas como ciertas.",
    "QUINTO": "requerir que, en un plazo no mayor de cinco (5) días hábiles contado a partir del día siguiente de la notificación de la presente resolución: a) La Positiva cumpla con presentar la copia de la póliza de seguro, pronunciamiento formal de rechazo y sustentos que acrediten la autorización de la renovación de póliza y los cobros efectuados.",
    "SEXTO": "informar a las partes que el artículo 110 de la Ley 29571, Código de Protección y Defensa del Consumidor__F8__, faculta a la Comisión a calificar las infracciones de la referida norma como leves, graves o muy graves e imponer sanciones que van desde una amonestación hasta una multa por un máximo de 450 Unidades Impositivas Tributarias, sin perjuicio de las medidas correctivas, reparadoras y complementarias, que puedan ordenarse de acuerdo a lo estipulado en los artículos 114, 115 y 116 de la referida norma__F9__.",
    "SÉTIMO": "informar a las partes que conforme a lo establecido en el artículo 39 de la Ley sobre Facultades, Normas y Organización del Indecopi, aprobada por Decreto Legislativo 807, los gastos por los peritajes realizados, actuación de pruebas, inspecciones y otros derivados de la tramitación del proceso serán de cargo de la parte que solicita la prueba, salvo pacto en contrario. En todos los casos, la resolución final determinará si los gastos deben ser asumidos por alguna de las partes, o reembolsados a la otra parte o al Indecopi, según sea el caso, de manera adicional a la sanción que haya podido imponerse.",
    "OCTAVO": "comunicar a las partes que, de acuerdo a lo señalado por el artículo 29 del Decreto Legislativo 807__F11__, hasta antes de la emisión de la Resolución Final tienen la posibilidad de solicitar una audiencia de conciliación. En caso deleguen a favor de una tercera persona su actuación en la diligencia programada, ésta deberá presentar un poder especial con firma legalizada ante Notario Público, donde conste expresamente su facultad para asistir y conciliar en su representación. Ello bajo apercibimiento de no realizar la audiencia de conciliación y levantar el acta de inasistencia correspondiente."
  },
  "footnotes": {
    "__F1__": "Denuncia remitida a esta Comisión mediante DOCUMENTO DE TRASLADO N° 162-2026-PS1/INDECOPI de fecha 02 de junio de 2026, recepcionada el 12 de junio de 2026.",
    "__F2__": "Publicado el 2 de setiembre del 2010 en el Diario Oficial El Peruano, vigente desde el 2 de octubre del 2010 y modificado por Decreto Legislativo 1308.",
    "__F3__": "LEY 29571, CÓDIGO DE PROTECCIÓN Y DEFENSA DEL CONSUMIDOR, publicado el 2 de setiembre de 2010 y modificado por Decreto Legislativo N 1308\nArtículo 105.- Autoridad competente.\nEl Instituto Nacional de Defensa de la Competencia y de la Protección de la Propiedad Intelectual (Indecopi) es la autoridad con competencia primaria y de alcance nacional para conocer las presuntas infracciones a las disposiciones contenidas en el presente Código, así como para imponer las sanciones y medidas correctivas establecidas en el presente capítulo, conforme al Decreto Legislativo N 1033, Ley de Organización y Funciones del Indecopi. Dicha competencia solo puede ser negada cuando ella haya sido asignada o se asigne a favor de otro organismo por norma expresa con rango de ley.\n(...).\n\nLEY DE ORGANIZACIÓN Y FUNCIONES DEL INDECOPI, APROBADA POR DECRETO LEGISLATIVO N 1033\nArtículo 27.- De la Comisión de Protección al Consumidor.-\nCorresponde a la Comisión de Protección al Consumidor velar por el cumplimiento de la Ley de Protección al Consumidor y de las leyes que, en general, protegen a los consumidores de la falta de idoneidad de los bienes y servicios en función de la información brindada, de las omisiones de información y de la discriminación en el consumo, así como de aquellas que complementen o sustituyan a las anteriores.",
    "__F4__": "LEY N° 29571. CÓDIGO DE PROTECCIÓN Y DEFENSA DEL CONSUMIDOR\nArtículo 18.- Idoneidad\nSe entiende por idoneidad la correspondencia entre lo que un consumidor espera y lo que efectivamente recibe, en función a lo que se le hubiera ofrecido, la publicidad e información transmitida, las condiciones y circunstancias de la transacción, las características y naturaleza del producto o servicio, el precio, entre otros factores, atendiendo a las circunstancias del caso.",
    "__F5__": "LEY 29571, CÓDIGO DE PROTECCIÓN Y DEFENSA DEL CONSUMIDOR\nArtículo 56.- Métodos comerciales coercitivos\n(...)\nb. Obligar al consumidor a asumir prestaciones que no ha pactado o a efectuar pagos por productos o servicios que no han sido requeridos previamente. En ningún caso puede interpretarse el silencio del consumidor como aceptación de dichas prestaciones o pagos, salvo que lo haya autorizado previamente de manera expresa."
  }
}

with open(Path("casos") / "2142-2026.json", "w", encoding="utf-8") as f:
    json.dump(caso, f, ensure_ascii=False, indent=2)
