import json
from pathlib import Path

caso = {
  "expediente": "2190-2026/CC1",
  "denunciante": "GLADIS YSABEL BENITES CAJA (SEÑORA BENITES)",
  "denunciado": "RÍMAC SEGUROS Y REASEGUROS S.A. (RÍMAC)",
  "fecha_res": "Lima, 13 de julio de 2026",
  "fecha_denuncia": "12 de junio de 2026",
  "intro_denuncia": "la señora Benites denunció a Rímac por presuntas infracciones a la Ley 29571, Código de Protección y Defensa del Consumidor (en adelante, Código)__F2__,",
  "hechos": [
    "El 24 de julio de 2024, el vehículo asegurado de placa CMJ-003 sufrió un accidente de tránsito (despiste y choque) con pérdida total y lesiones personales. Al respecto, el Informe Policial exoneró de responsabilidad al conductor.",
    "El 5 de agosto de 2024, mediante Carta N° SVCRCSL-877260, Rímac rechazó la cobertura invocando la supuesta falta de licencia de conducir vigente, sustentándose en una presunta constancia del Ministerio de Transportes y Comunicaciones (MTC).",
    "Pese a haber sido requerida expresamente, la aseguradora se habría negado a remitir copia de dicha constancia del MTC a la denunciante.",
    "Asimismo, Rímac no habría enviado ningún representante ni ajustador al lugar del accidente para verificar las circunstancias del siniestro.",
    "Finalmente, la aseguradora no habría brindado respuesta a múltiples comunicaciones formales presentadas por la denunciante (cartas de reconsideración y solicitudes de constancia) y habría interpretado las cláusulas de la póliza de manera desfavorable a la consumidora."
  ],
  "medida_correctiva": "La señora Benites solicitó, en calidad de medida correctiva, que Rímac cumpla con honrar la cobertura del siniestro N° 879294 (póliza N° 2101-1442991), incluyendo el resarcimiento por daños materiales (pérdida total), daños personales a los ocupantes y demás coberturas contratadas, así como la presentación de la constancia emitida por el MTC. Asimismo, requirió de manera expresa el reembolso de costas y costos del presente procedimiento.",
  "imputaciones_analisis": [
    "La Secretaría Técnica de la Comisión de Protección al Consumidor 1 (en adelante, la Secretaría Técnica), en ejercicio de sus facultades__F3__, considera que el hecho denunciado, consistente en que Rímac habría rechazado la cobertura del siniestro del 24 de julio de 2024; involucraría una presunta afectación a sus expectativas, quien no habría encontrado una correspondencia entre lo que esperaba recibir de parte del proveedor y lo que realmente recibió. Por consiguiente, corresponde calificar el hecho materia de denuncia como una presunta infracción al deber de idoneidad, tipificado en los artículos 18 y 19 del Código__F4__.",
    "Asimismo, la Secretaría Técnica, en ejercicio de sus facultades, considera que el hecho denunciado, consistente en que Rímac no habría remitido copia de la constancia del MTC invocada para el rechazo. Por consiguiente, corresponde calificar el hecho materia de denuncia como una presunta infracción al deber de información, tipificado en el artículo 2 del Código__F5__.",
    "Además, la Secretaría Técnica, en ejercicio de sus facultades, considera que el hecho denunciado, consistente en que Rímac habría interpretado las condiciones de la póliza vulnerando la buena fe, el justo equilibrio y la interpretación favorable al asegurado; involucraría una presunta afectación a sus expectativas, quien no habría encontrado una correspondencia entre lo que esperaba recibir de parte del proveedor y lo que realmente recibió. Por consiguiente, corresponde calificar el hecho materia de denuncia como una presunta infracción al deber de idoneidad, tipificado en los artículos 18 y 19 del Código.",
    "Adicionalmente, la Secretaría Técnica, en ejercicio de sus facultades, considera que el hecho denunciado, consistente en que Rímac no habría enviado representante ni ajustador al lugar del siniestro para la verificación respectiva; involucraría una presunta afectación a sus expectativas, quien no habría encontrado una correspondencia entre lo que esperaba recibir de parte del proveedor y lo que realmente recibió. Por consiguiente, corresponde calificar el hecho materia de denuncia como una presunta infracción al deber de idoneidad, tipificado en los artículos 18 y 19 del Código.",
    "Finalmente, la Secretaría Técnica, en ejercicio de sus facultades, considera que el hecho denunciado, consistente en que Rímac no habría brindado respuesta a las diversas comunicaciones y solicitudes de reconsideración presentadas por la denunciante; involucraría una presunta afectación a sus expectativas, quien no habría encontrado una correspondencia entre lo que esperaba recibir de parte del proveedor y lo que realmente recibió. Por consiguiente, corresponde calificar el hecho materia de denuncia como una presunta infracción al deber de idoneidad, tipificado en los artículos 18 y 19 del Código."
  ],
  "req_info": [
    "A efectos de tener mayores elementos que sirvan para la resolución definitiva del presente caso, la Secretaría Técnica, en ejercicio de las facultades que la ley le confiere, conviene requerir a la proveedora denunciada que, en un plazo no mayor de cinco (5) días hábiles contado a partir del día siguiente de la notificación de la presente resolución, cumpla con lo siguiente:",
    "A Rímac: (i) presentar una copia debidamente suscrita de la Póliza Vehicular N° 2101-1442991 materia de denuncia; (ii) presentar los actuados del siniestro N° 879294; (iii) presentar el sustento documentario que acredite el envío de la Carta N° SVCRCSL-877260 con sus respectivos anexos (incluyendo la constancia del MTC referida); y, (iv) presentar los medios probatorios que acrediten haber dado respuesta a las comunicaciones y cartas de reconsideración presentadas por la denunciante."
  ],
  "imputaciones_res": [
    "Presunta infracción a los artículos 18° y 19° de la Ley N° 29571, Código de Protección y Defensa del Consumidor, en tanto RÍMAC SEGUROS Y REASEGUROS S.A. habría rechazado la cobertura del siniestro de fecha 24 de julio de 2024.",
    "Presunta infracción al artículo 2° de la Ley N° 29571, Código de Protección y Defensa del Consumidor, en tanto RÍMAC SEGUROS Y REASEGUROS S.A. no habría remitido a la denunciante copia de la constancia del MTC que sirvió de sustento para el rechazo.",
    "Presunta infracción a los artículos 18° y 19° de la Ley N° 29571, Código de Protección y Defensa del Consumidor, en tanto RÍMAC SEGUROS Y REASEGUROS S.A. habría interpretado las condiciones de la póliza vulnerando la buena fe, el justo equilibrio y la interpretación favorable al asegurado.",
    "Presunta infracción a los artículos 18° y 19° de la Ley N° 29571, Código de Protección y Defensa del Consumidor, en tanto RÍMAC SEGUROS Y REASEGUROS S.A. no habría enviado representante ni ajustador al lugar del siniestro.",
    "Presunta infracción a los artículos 18° y 19° de la Ley N° 29571, Código de Protección y Defensa del Consumidor, en tanto RÍMAC SEGUROS Y REASEGUROS S.A. no habría brindado respuesta a las comunicaciones y cartas de reconsideración presentadas por la denunciante."
  ],
  "notificaciones": [
    "poner en conocimiento de las partes que, antes de la emisión de la Resolución Final, tienen la posibilidad de formular su desistimiento o presentar el acuerdo arribado mediante la conciliación, mediación, transacción o cualquier otro que, de forma indubitable, deje constancia que se ha solucionado la controversia materia de denuncia.",
    "requerir a la señora Gladis Ysabel Benites Caja para que, dentro del plazo de dos (2) días hábiles siguientes a la fecha en que reciba la notificación en su bandeja de correo electrónico, efectúe la confirmación de recepción de la notificación remitida por este despacho a su correo electrónico Gladys_0773@hotmail.com y jorge.via.laos@gmail.com, de conformidad con el segundo párrafo del numeral 4 del artículo 20 del Texto Único Ordenado de la Ley del Procedimiento Administrativo General, aprobado mediante Decreto Supremo 006-2026-JUS, bajo apercibimiento de rehacer el acto de notificación y notificarle conforme al numeral 1 del artículo 20 del citado cuerpo normativo__F12__.",
    "requerir a RÍMAC SEGUROS Y REASEGUROS S.A. para que efectúe el acuse de recibo mediante la confirmación de recepción de la notificación remitida por este despacho a su Casilla Electrónica, dentro de los cinco (5) primeros días hábiles siguientes a la fecha en que reciben la notificación."
  ],
  "resolutivos": {
    "PRIMERO": "admitir a trámite la denuncia del 12 de junio de 2026 interpuesta por la señora Gladis Ysabel Benites Caja contra RÍMAC SEGUROS Y REASEGUROS S.A., en atención a lo siguiente:",
    "SEGUNDO": "tener por ofrecidos los medios probatorios presentados en el escrito de denuncia del 12 de junio de 2026.",
    "TERCERO": "requerir a RÍMAC SEGUROS Y REASEGUROS S.A. que cumpla con lo siguiente:\n(i)\tpresentar documentos que acrediten su inscripción en los Registros Públicos o una declaración jurada que indique que cuenta con dicha inscripción;\n(ii)\tpresentar copia simple de las facultades de representación de su representante legal en el presente procedimiento o la declaración jurada que indique que cuenta con dichas facultades y que estas se encuentran vigentes;\n(iii)\tconsignar el Número de Registro Único de Contribuyentes (RUC); y,\n(iv)\tfijar domicilio procesal para el procedimiento, de conformidad con el numeral 1 del artículo 442 del Código Procesal Civil. Para ello podrá señalar domicilio físico o una dirección electrónica a la que pueda remitirse las notificaciones;",
    "CUARTO": "correr traslado de la denuncia a RÍMAC SEGUROS Y REASEGUROS S.A., para que, de conformidad con lo dispuesto por el artículo 26 de la Ley sobre Facultades, Normas y Organización del Indecopi, aprobada por Decreto Legislativo 807, presente sus descargos en un plazo no mayor de cinco (5) días hábiles contados desde la notificación.",
    "QUINTO": "requerir que, en un plazo no mayor de cinco (5) días hábiles contado a partir del día siguiente de la notificación de la presente resolución: a) Rímac cumpla con presentar la copia de la póliza de seguro, sustentos de rechazo de cobertura y de atenciones a comunicaciones de la denunciante.",
    "SEXTO": "informar a las partes que el artículo 110 de la Ley 29571, Código de Protección y Defensa del Consumidor__F8__, faculta a la Comisión a calificar las infracciones de la referida norma como leves, graves o muy graves e imponer sanciones que van desde una amonestación hasta una multa por un máximo de 450 Unidades Impositivas Tributarias, sin perjuicio de las medidas correctivas, reparadoras y complementarias, que puedan ordenarse de acuerdo a lo estipulado en los artículos 114, 115 y 116 de la referida norma__F9__.",
    "SÉTIMO": "informar a las partes que conforme a lo establecido en el artículo 39 de la Ley sobre Facultades, Normas y Organización del Indecopi, aprobada por Decreto Legislativo 807, los gastos por los peritajes realizados, actuación de pruebas, inspecciones y otros derivados de la tramitación del proceso serán de cargo de la parte que solicita la prueba, salvo pacto en contrario. En todos los casos, la resolución final determinará si los gastos deben ser asumidos por alguna de las partes, o reembolsados a la otra parte o al Indecopi, según sea el caso, de manera adicional a la sanción que haya podido imponerse.",
    "OCTAVO": "comunicar a las partes que, de acuerdo a lo señalado por el artículo 29 del Decreto Legislativo 807__F11__, hasta antes de la emisión de la Resolución Final tienen la posibilidad de solicitar una audiencia de conciliación. En caso deleguen a favor de una tercera persona su actuación en la diligencia programada, ésta deberá presentar un poder especial con firma legalizada ante Notario Público, donde conste expresamente su facultad para asistir y conciliar en su representación. Ello bajo apercibimiento de no realizar la audiencia de conciliación y levantar el acta de inasistencia correspondiente."
  },
  "footnotes": {
    "__F2__": "Publicado el 2 de setiembre del 2010 en el Diario Oficial El Peruano, vigente desde el 2 de octubre del 2010 y modificado por Decreto Legislativo 1308.",
    "__F3__": "LEY 29571, CÓDIGO DE PROTECCIÓN Y DEFENSA DEL CONSUMIDOR, publicado el 2 de setiembre de 2010 y modificado por Decreto Legislativo N 1308\nArtículo 105.- Autoridad competente.\nEl Instituto Nacional de Defensa de la Competencia y de la Protección de la Propiedad Intelectual (Indecopi) es la autoridad con competencia primaria y de alcance nacional para conocer las presuntas infracciones a las disposiciones contenidas en el presente Código, así como para imponer las sanciones y medidas correctivas establecidas en el presente capítulo, conforme al Decreto Legislativo N 1033, Ley de Organización y Funciones del Indecopi. Dicha competencia solo puede ser negada cuando ella haya sido asignada o se asigne a favor de otro organismo por norma expresa con rango de ley.\n(...).\n\nLEY DE ORGANIZACIÓN Y FUNCIONES DEL INDECOPI, APROBADA POR DECRETO LEGISLATIVO N 1033\nArtículo 27.- De la Comisión de Protección al Consumidor.-\nCorresponde a la Comisión de Protección al Consumidor velar por el cumplimiento de la Ley de Protección al Consumidor y de las leyes que, en general, protegen a los consumidores de la falta de idoneidad de los bienes y servicios en función de la información brindada, de las omisiones de información y de la discriminación en el consumo, así como de aquellas que complementen o sustituyan a las anteriores.",
    "__F4__": "LEY 29571, CÓDIGO DE PROTECCIÓN Y DEFENSA DEL CONSUMIDOR, publicado el 2 de setiembre de 2010 y modificado por Decreto Legislativo N 1308\nArtículo 18.- Idoneidad\nSe entiende por idoneidad la correspondencia entre lo que un consumidor espera y lo que efectivamente recibe, en función a lo que se le hubiera ofrecido, la publicidad e información transmitida, las condiciones y circunstancias de la transacción, las características y naturaleza del producto o servicio, el precio, entre otros factores, atendiendo a las circunstancias del caso.\nLa idoneidad es evaluada en función a la propia naturaleza del producto o servicio y a su aptitud para satisfacer la finalidad para la cual ha sido puesto en el mercado. Las autorizaciones por parte de los organismos del Estado para la fabricación de un producto o la prestación de un servicio, en los casos que sea necesario, no eximen de responsabilidad al proveedor frente al consumidor.\n\nArtículo 19.- Obligación de los proveedores\nEl proveedor responde por la idoneidad y calidad de los productos y servicios ofrecidos; por la autenticidad de las marcas y leyendas que exhiben sus productos o del signo que respalda al prestador del servicio, por la falta de conformidad entre la publicidad comercial de los productos y servicios y éstos, así como por el contenido y la vida útil del producto indicado en el envase, en lo que corresponda.",
    "__F5__": "LEY N° 29571, CÓDIGO DE PROTECCIÓN Y DEFENSA DEL CONSUMIDOR\nArtículo 2.- Información relevante\n2.1 El proveedor tiene la obligación de ofrecer al consumidor toda la información relevante para tomar una decisión o realizar una elección adecuada de consumo, así como para efectuar un uso o consumo adecuado de los productos o servicios."
  }
}

with open(Path("casos") / "2190-2026.json", "w", encoding="utf-8") as f:
    json.dump(caso, f, ensure_ascii=False, indent=2)
