import json
from pathlib import Path

caso = {
  "expediente": "1963-2026/CC1",
  "denunciante": "MAYRA ARACELLY ESTELO RODRÍGUEZ",
  "denunciado": "LA POSITIVA SEGUROS Y REASEGUROS S.A.A. (LA POSITIVA)",
  "fecha_res": "Lima, 24 de julio de 2026",
  "fecha_denuncia": "20 de marzo de 2026__F1__",
  "intro_denuncia": "la señora Mayra Aracelly Estelo Rodríguez denunció a La Positiva por presuntas infracciones a la Ley 29571, Código de Protección y Defensa del Consumidor (en adelante, Código)__F2__,",
  "hechos": [
    "El 6 de febrero de 2026, la denunciante se comunicó con La Positiva al no estar de acuerdo con el incremento de la prima de renovación de su seguro vehicular (póliza N° 60037509) para el periodo 2026-2027.",
    "El 11 de febrero de 2026, tras presentar un reclamo, la aseguradora le informó que accedería a reducir el monto anual de la prima a USD 818,11. La denunciante aceptó la propuesta y solicitó la emisión de la póliza actualizada para enviarla al Banco de Crédito del Perú (BCP), entidad a favor de la cual se encontraba endosada la póliza.",
    "Sin embargo, el 4 de marzo de 2026, La Positiva le comunicó que no podría reducir el precio debido a la falta de autorización de un intermediario (Maquinaria Nacional S.A. Perú). Al solicitar los datos de contacto de dicho intermediario, un asesor telefónico de la aseguradora le indicó que los buscara en Google.",
    "Posteriormente, el 6 de marzo de 2026, la denunciante solicitó la anulación de la póliza para contratar un seguro directo sin intermediario; no obstante, La Positiva le requirió una carta de liberación del BCP. Al contactar al BCP, este le informó que no era posible emitir dicha carta sin anular también la póliza vigente (2025-2026), debido a que la aseguradora había consignado el mismo número de póliza para ambos periodos.",
    "Finalmente, ante la proximidad del vencimiento del plazo otorgado por el BCP y la falta de respuesta de La Positiva a sus comunicaciones posteriores, el 10 de marzo de 2026 la denunciante se vio obligada a aceptar la póliza con la prima incrementada para no dejar su vehículo desprotegido."
  ],
  "medida_correctiva": "La denunciante solicitó, en calidad de medida correctiva, el reembolso del exceso cobrado en las cuotas del seguro y la devolución de los gastos incurridos durante el procedimiento. Asimismo, requirió de manera expresa el reembolso de costas y costos del presente procedimiento.",
  "imputaciones_analisis": [
    "La Secretaría Técnica de la Comisión de Protección al Consumidor 1 (en adelante, la Secretaría Técnica), en ejercicio de sus facultades__F3__, considera que el hecho denunciado, consistente en que La Positiva Seguros y Reaseguros S.A.A. habría desconocido el acuerdo de reducción de la prima anual a USD 818,11 para la renovación de la póliza vehicular N° 60037509 (periodo 2026-2027); involucraría una presunta afectación a sus expectativas, quien no habría encontrado una correspondencia entre lo que esperaba recibir de parte del proveedor y lo que realmente recibió. Por consiguiente, corresponde calificar el hecho materia de denuncia como una presunta infracción al deber de idoneidad, tipificado en los artículos 18 y 19 del Código__F4__.",
    "Asimismo, la Secretaría Técnica, en ejercicio de sus facultades, considera que el hecho denunciado, consistente en que La Positiva Seguros y Reaseguros S.A.A. no habría brindado información oportuna ni adecuada respecto a los datos de contacto del intermediario Maquinaria Nacional S.A. Perú, indicándole a la consumidora que buscara dicha información en Google. Por consiguiente, corresponde calificar el hecho materia de denuncia como una presunta infracción al deber de información, tipificado en el artículo 2 del Código__F5__.",
    "Además, la Secretaría Técnica, en ejercicio de sus facultades, considera que el hecho denunciado, consistente en que La Positiva Seguros y Reaseguros S.A.A. habría asignado el mismo número de póliza (N° 60037509) tanto para el periodo vigente como para el periodo de renovación, lo cual habría impedido a la denunciante anular la renovación sin afectar su cobertura actual; involucraría una presunta afectación a sus expectativas, quien no habría encontrado una correspondencia entre lo que esperaba recibir de parte del proveedor y lo que realmente recibió. Por consiguiente, corresponde calificar el hecho materia de denuncia como una presunta infracción al deber de idoneidad, tipificado en los artículos 18 y 19 del Código.",
    "Finalmente, la Secretaría Técnica, en ejercicio de sus facultades, considera que el hecho denunciado, consistente en que La Positiva Seguros y Reaseguros S.A.A. no habría brindado respuesta a las comunicaciones cursadas por la denunciante con posterioridad al 6 de marzo de 2026; involucraría una presunta afectación a sus expectativas, quien no habría encontrado una correspondencia entre lo que esperaba recibir de parte del proveedor y lo que realmente recibió. Por consiguiente, corresponde calificar el hecho materia de denuncia como una presunta infracción al deber de idoneidad, tipificado en los artículos 18 y 19 del Código."
  ],
  "req_info": [
    "A efectos de tener mayores elementos que sirvan para la resolución definitiva del presente caso, la Secretaría Técnica, en ejercicio de las facultades que la ley le confiere, requiere a la proveedora denunciada presentar en el plazo de cinco (5) días hábiles:",
    "A La Positiva: (i) copia de la póliza de seguro vehicular N° 60037509, incluyendo las condiciones generales y particulares de los periodos 2025-2026 y 2026-2027; (ii) los registros de audio o sustento documentario de las comunicaciones mantenidas con la denunciante en febrero y marzo de 2026, específicamente respecto al acuerdo de reducción de prima y la intervención del intermediario; y, (iii) el sustento de la asignación de la numeración de la póliza de renovación."
  ],
  "imputaciones_res": [
    "Presunta infracción a los artículos 18° y 19° de la Ley N° 29571, Código de Protección y Defensa del Consumidor, en tanto La Positiva Seguros y Reaseguros S.A.A. habría desconocido el acuerdo de reducción de la prima anual a USD 818,11 para la renovación de la póliza vehicular N° 60037509 (periodo 2026-2027).",
    "Presunta infracción al artículo 2° de la Ley N° 29571, Código de Protección y Defensa del Consumidor, en tanto La Positiva Seguros y Reaseguros S.A.A. no habría brindado información adecuada respecto a los datos de contacto del intermediario del seguro.",
    "Presunta infracción a los artículos 18° y 19° de la Ley N° 29571, Código de Protección y Defensa del Consumidor, en tanto La Positiva Seguros y Reaseguros S.A.A. habría asignado el mismo número de póliza para la renovación, impidiendo a la denunciante gestionar su anulación sin afectar la cobertura vigente.",
    "Presunta infracción a los artículos 18° y 19° de la Ley N° 29571, Código de Protección y Defensa del Consumidor, en tanto La Positiva Seguros y Reaseguros S.A.A. no habría brindado respuesta a las comunicaciones cursadas por la denunciante con posterioridad al 6 de marzo de 2026."
  ],
  "notificaciones": [
    "poner en conocimiento de las partes que, antes de la emisión de la Resolución Final, tienen la posibilidad de formular su desistimiento o presentar el acuerdo arribado mediante la conciliación, mediación, transacción o cualquier otro que, de forma indubitable, deje constancia que se ha solucionado la controversia materia de denuncia.",
    "requerir a la señora Mayra Aracelly Estelo Rodríguez para que, dentro del plazo de dos (2) días hábiles siguientes a la fecha en que reciba la notificación en su bandeja de correo electrónico, efectúe la confirmación de recepción de la notificación remitida por este despacho a su correo electrónico MAYRA_11_03@HOTMAIL.COM, de conformidad con el segundo párrafo del numeral 4 del artículo 20 del Texto Único Ordenado de la Ley del Procedimiento Administrativo General, aprobado mediante Decreto Supremo 006-2026-JUS, bajo apercibimiento de rehacer el acto de notificación y notificarle conforme al numeral 1 del artículo 20 del citado cuerpo normativo__F12__.",
    "requerir a La Positiva Seguros y Reaseguros S.A.A. para que efectúe el acuse de recibo mediante la confirmación de recepción de la notificación remitida por este despacho a su Casilla Electrónica, dentro de los cinco (5) primeros días hábiles siguientes a la fecha en que reciben la notificación."
  ],
  "resolutivos": {
    "PRIMERO": "admitir a trámite la denuncia del 20 de marzo de 2026, subsanada el 5 de junio de 2026, interpuesta por la señora Mayra Aracelly Estelo Rodríguez contra La Positiva Seguros y Reaseguros S.A.A., en atención a lo siguiente:",
    "SEGUNDO": "tener por ofrecidos los medios probatorios presentados en el escrito de denuncia del 20 de marzo de 2026 y en el escrito de subsanación del 5 de junio de 2026.",
    "TERCERO": "requerir a La Positiva Seguros y Reaseguros S.A.A. que cumpla con lo siguiente:\n(i)\tpresentar documentos que acrediten su inscripción en los Registros Públicos o una declaración jurada que indique que cuenta con dicha inscripción;\n(ii)\tpresentar copia simple de las facultades de representación de su representante legal en el presente procedimiento o la declaración jurada que indique que cuenta con dichas facultades y que estas se encuentran vigentes;\n(iii)\tconsignar el Número de Registro Único de Contribuyentes (RUC); y,\n(iv)\tfijar domicilio procesal para el procedimiento, de conformidad con el numeral 1 del artículo 442 del Código Procesal Civil. Para ello podrá señalar domicilio físico o una dirección electrónica a la que pueda remitirse las notificaciones;",
    "CUARTO": "correr traslado de la denuncia a La Positiva Seguros y Reaseguros S.A.A., para que, de conformidad con lo dispuesto por el artículo 26 de la Ley sobre Facultades, Normas y Organización del Indecopi, aprobada por Decreto Legislativo 807, presente sus descargos en un plazo no mayor de cinco (5) días hábiles contados desde la notificación.",
    "QUINTO": "requerir que, en un plazo no mayor de cinco (5) días hábiles contado a partir del día siguiente de la notificación de la presente resolución, el proveedor denunciado cumpla con: (i) presentar una copia completa, legible y debidamente suscrita de la Póliza 60037509 del Seguro vehicular del Seguro Vehicular, así como el cargo de remisión de la póliza; (ii) presentar los medios probatorios que acrediten que realizó la modificación del monto de la prima anual de la Póliza 60037509 del Seguro vehicular, conforme a lo informado a la denunciante el 11 de febrero de 2026; y, (iii) presentar todas las comunicaciones cursadas con la parte denunciante en virtud de los hechos materia de denuncia.",
    "SEXTO": "informar a las partes que el artículo 110 de la Ley 29571, Código de Protección y Defensa del Consumidor__F8__, faculta a la Comisión a calificar las infracciones de la referida norma como leves, graves o muy graves e imponer sanciones que van desde una amonestación hasta una multa por un máximo de 450 Unidades Impositivas Tributarias, sin perjuicio de las medidas correctivas, reparadoras y complementarias, que puedan ordenarse de acuerdo a lo estipulado en los artículos 114, 115 y 116 de la referida norma__F9__.",
    "SÉTIMO": "informar a las partes que conforme a lo establecido en el artículo 39 de la Ley sobre Facultades, Normas y Organización del Indecopi, aprobada por Decreto Legislativo 807, los gastos por los peritajes realizados, actuación de pruebas, inspecciones y otros derivados de la tramitación del proceso serán de cargo de la parte que solicita la prueba, salvo pacto en contrario. En todos los casos, la resolución final determinará si los gastos deben ser asumidos por alguna de las partes, o reembolsados a la otra parte o al Indecopi, según sea el caso, de manera adicional a la sanción que haya podido imponerse.",
    "OCTAVO": "comunicar a las partes que, de acuerdo a lo señalado por el artículo 29 del Decreto Legislativo 807__F11__, hasta antes de la emisión de la Resolución Final tienen la posibilidad de solicitar una audiencia de conciliación. En caso deleguen a favor de una tercera persona su actuación en la diligencia programada, ésta deberá presentar un poder especial con firma legalizada ante Notario Público, donde conste expresamente su facultad para asistir y conciliar en su representación. Ello bajo apercibimiento de no realizar la audiencia de conciliación y levantar el acta de inasistencia correspondiente."
  },
  "footnotes": {
    "__F1__": "Denuncia remitida a esta Comisión mediante DOCUMENTO DE TRASLADO N° 068-2026-PS1/INDECOPI de fecha 22 de mayo de 2026, recepcionada el 29 de mayo de 2026.",
    "__F2__": "Publicado el 2 de setiembre del 2010 en el Diario Oficial El Peruano, vigente desde el 2 de octubre del 2010 y modificado por Decreto Legislativo 1308.",
    "__F3__": "LEY 29571, CÓDIGO DE PROTECCIÓN Y DEFENSA DEL CONSUMIDOR, publicado el 2 de setiembre de 2010 y modificado por Decreto Legislativo N 1308\nArtículo 105.- Autoridad competente.\nEl Instituto Nacional de Defensa de la Competencia y de la Protección de la Propiedad Intelectual (Indecopi) es la autoridad con competencia primaria y de alcance nacional para conocer las presuntas infracciones a las disposiciones contenidas en el presente Código, así como para imponer las sanciones y medidas correctivas establecidas en el presente capítulo, conforme al Decreto Legislativo N 1033, Ley de Organización y Funciones del Indecopi. Dicha competencia solo puede ser negada cuando ella haya sido asignada o se asigne a favor de otro organismo por norma expresa con rango de ley.\n(...).\n\nLEY DE ORGANIZACIÓN Y FUNCIONES DEL INDECOPI, APROBADA POR DECRETO LEGISLATIVO N 1033\nArtículo 27.- De la Comisión de Protección al Consumidor.-\nCorresponde a la Comisión de Protección al Consumidor velar por el cumplimiento de la Ley de Protección al Consumidor y de las leyes que, en general, protegen a los consumidores de la falta de idoneidad de los bienes y servicios en función de la información brindada, de las omisiones de información y de la discriminación en el consumo, así como de aquellas que complementen o sustituyan a las anteriores.",
    "__F4__": "LEY N° 29571. CÓDIGO DE PROTECCIÓN Y DEFENSA DEL CONSUMIDOR\nArtículo 18.- Idoneidad\nSe entiende por idoneidad la correspondencia entre lo que un consumidor espera y lo que efectivamente recibe, en función a lo que se le hubiera ofrecido, la publicidad e información transmitida, las condiciones y circunstancias de la transacción, las características y naturaleza del producto o servicio, el precio, entre otros factores, atendiendo a las circunstancias del caso.",
    "__F5__": "LEY N° 29571, CÓDIGO DE PROTECCIÓN Y DEFENSA DEL CONSUMIDOR\nArtículo 2.- Información relevante\n2.1 El proveedor tiene la obligación de ofrecer al consumidor toda la información relevante para tomar una decisión o realizar una elección adecuada de consumo, así como para efectuar un uso o consumo adecuado de los productos o servicios."
  }
}

with open(Path("casos") / "1963-2026.json", "w", encoding="utf-8") as f:
    json.dump(caso, f, ensure_ascii=False, indent=2)
