import json
from pathlib import Path

caso = {
  "expediente": "2222-2026/CC1",
  "denunciante": "CLEOFE CIRILO QUISPE NINA",
  "denunciado": "MAPFRE PERÚ COMPAÑÍA DE SEGUROS Y REASEGUROS S.A. (MAPFRE)",
  "fecha_res": "Lima, 24 de julio de 2026",
  "fecha_denuncia": "16 de junio de 2026__F1__",
  "intro_denuncia": "el señor Cleofe Cirilo Quispe Nina denunció a Mapfre por presuntas infracciones a la Ley 29571, Código de Protección y Defensa del Consumidor (en adelante, Código)__F2__,",
  "hechos": [
    "El 18 de diciembre de 2025, la Primera Sala Constitucional de la Corte Superior de Justicia de Lima emitió la Resolución 08 (recaída en el expediente 15208-2018), mediante la cual ordenó a Mapfre el pago de la cobertura del Seguro Complementario de Trabajo de Riesgo - Pensión a favor del denunciante.",
    "No obstante, la aseguradora no habría cumplido con efectuar dicho pago, pese al mandato judicial emitido.",
    "Posteriormente, el 9 de febrero de 2026, el denunciante presentó una solicitud a Mapfre requiriendo el cumplimiento del pago ordenado.",
    "Sin embargo, a la fecha de la denuncia, la aseguradora no habría brindado respuesta alguna a la solicitud presentada por el denunciante."
  ],
  "medida_correctiva": "El denunciante solicitó, en calidad de medida correctiva, que se ordene a la aseguradora el cumplimiento del pago de la cobertura de la pensión de invalidez por enfermedad profesional, así como el pago de los devengados e intereses legales correspondientes. Asimismo, requirió el pago de las costas y costos del procedimiento.",
  "imputaciones_analisis": [
    "La Secretaría Técnica de la Comisión de Protección al Consumidor 1 (en adelante, la Secretaría Técnica), en ejercicio de sus facultades__F3__, considera que el hecho denunciado, consistente en que Mapfre Perú Compañía de Seguros y Reaseguros S.A. no habría cumplido con efectuar el pago de la cobertura del Seguro Complementario de Trabajo de Riesgo - Pensión a favor del denunciante, pese a lo ordenado por la Primera Sala Constitucional de Lima en la sentencia de vista contenida en el expediente 15208-2018; involucraría una presunta afectación a sus expectativas, quien no habría encontrado una correspondencia entre lo que esperaba recibir de parte del proveedor y lo que realmente recibió. Por consiguiente, corresponde calificar el hecho materia de denuncia como una presunta infracción al deber de idoneidad, tipificado en los artículos 18 y 19 del Código__F4__.",
    "Asimismo, la Secretaría Técnica, en ejercicio de sus facultades, considera que el hecho denunciado, consistente en que Mapfre Perú Compañía de Seguros y Reaseguros S.A. no habría cumplido con brindar una respuesta a la solicitud presentada por el denunciante el 9 de febrero de 2026; involucraría una presunta afectación a sus expectativas. Por consiguiente, corresponde calificar el hecho materia de denuncia como una presunta infracción al deber de idoneidad, tipificado en los artículos 18 y 19 del Código."
  ],
  "req_info": [
    "A efectos de tener mayores elementos que sirvan para la resolución definitiva del presente caso, la Secretaría Técnica, en ejercicio de las facultades que la ley le confiere, requiere a la proveedora denunciada presentar en el plazo de cinco (5) días hábiles:",
    "A Mapfre: (i) los descargos respecto al presunto incumplimiento del pago de la cobertura del Seguro Complementario de Trabajo de Riesgo ordenado judicialmente, adjuntando los medios probatorios que lo sustenten; y, (ii) la constancia de respuesta a la solicitud del 9 de febrero de 2026, así como el cargo de notificación correspondiente."
  ],
  "imputaciones_res": [
    "Presunta infracción a los artículos 18° y 19° de la Ley N° 29571, Código de Protección y Defensa del Consumidor, en tanto Mapfre Perú Compañía de Seguros y Reaseguros S.A. no habría cumplido con efectuar el pago de la cobertura del Seguro Complementario de Trabajo de Riesgo - Pensión a favor del denunciante, pese a lo ordenado por la Primera Sala Constitucional de Lima en la sentencia de vista contenida en el expediente 15208-2018.",
    "Presunta infracción a los artículos 18° y 19° de la Ley N° 29571, Código de Protección y Defensa del Consumidor, en tanto Mapfre Perú Compañía de Seguros y Reaseguros S.A. no habría cumplido con brindar una respuesta a la solicitud presentada por el denunciante el 9 de febrero de 2026."
  ],
  "notificaciones": [
    "requerir al señor Cleofe Cirilo Quispe Nina para que, dentro del plazo de dos (2) días hábiles siguientes a la fecha en que reciba la notificación en su bandeja de correo electrónico, efectúe la confirmación de recepción de la notificación remitida por este despacho a su correo electrónico notificacion.consumidor@indecopi.gob.pe, de conformidad con el segundo párrafo del numeral 4 del artículo 20 del Texto Único Ordenado de la Ley del Procedimiento Administrativo General, aprobado mediante Decreto Supremo 006-2026-JUS, bajo apercibimiento de rehacer el acto de notificación y notificarle conforme al numeral 1 del artículo 20 del citado cuerpo normativo__F12__.",
    "requerir a Mapfre Perú Compañía de Seguros y Reaseguros S.A. para que efectúe el acuse de recibo mediante la confirmación de recepción de la notificación remitida por este despacho a su Casilla Electrónica, dentro de los cinco (5) primeros días hábiles siguientes a la fecha en que reciben la notificación."
  ],
  "resolutivos": {
    "PRIMERO": "admitir a trámite la denuncia del 16 de junio de 2026 interpuesta por el señor Cleofe Cirilo Quispe Nina contra Mapfre Perú Compañía de Seguros y Reaseguros S.A., en atención a lo siguiente:",
    "SEGUNDO": "tener por ofrecidos los medios probatorios presentados en el escrito de denuncia del 16 de junio de 2026.",
    "TERCERO": "requerir a Mapfre Perú Compañía de Seguros y Reaseguros S.A. que cumpla con lo siguiente:\n(i)\tpresentar documentos que acrediten su inscripción en los Registros Públicos o una declaración jurada que indique que cuenta con dicha inscripción;\n(ii)\tpresentar copia simple de las facultades de representación de su representante legal en el presente procedimiento o la declaración jurada que indique que cuenta con dichas facultades y que estas se encuentran vigentes;\n(iii)\tconsignar el Número de Registro Único de Contribuyentes (RUC); y,\n(iv)\tfijar domicilio procesal para el procedimiento, de conformidad con el numeral 1 del artículo 442 del Código Procesal Civil. Para ello podrá señalar domicilio físico o una dirección electrónica a la que pueda remitirse las notificaciones;",
    "CUARTO": "correr traslado de la presente resolución a Mapfre Perú Compañía de Seguros y Reaseguros S.A. para que, de conformidad con lo dispuesto por el artículo 26° de la Ley sobre Facultades, Normas y Organización del Indecopi, aprobado por Decreto Legislativo N° 8079, presente sus descargos sobre la imputación de cargos realizada en un plazo no mayor a cinco (5) días hábiles contado a partir del día siguiente de la notificación de la presente resolución, vencido el cual, el Secretario Técnico declarará en rebeldía a los denunciados que no lo hubieran presentado. Debe precisarse que de conformidad con lo establecido por el artículo 223° del Texto Único Ordenado de la Ley N° 27444, Ley del Procedimiento Administrativo General, las alegaciones y los hechos relevantes de la reclamación, salvo que hayan sido específicamente negadas en la contestación, se tendrán por aceptadas o meritadas como ciertas.",
    "QUINTO": "requerir que, en un plazo no mayor de cinco (5) días hábiles contado a partir del día siguiente de la notificación de la presente resolución: a) Mapfre cumpla con presentar los descargos respecto al presunto incumplimiento de pago de la pensión ordenada judicialmente y la constancia de respuesta a la solicitud del 9 de febrero de 2026, adjuntando los medios probatorios correspondientes.",
    "SEXTO": "informar a las partes que el artículo 110 de la Ley 29571, Código de Protección y Defensa del Consumidor__F8__, faculta a la Comisión a calificar las infracciones de la referida norma como leves, graves o muy graves e imponer sanciones que van desde una amonestación hasta una multa por un máximo de 450 Unidades Impositivas Tributarias, sin perjuicio de las medidas correctivas, reparadoras y complementarias, que puedan ordenarse de acuerdo a lo estipulado en los artículos 114, 115 y 116 de la referida norma__F9__.",
    "SÉTIMO": "informar a las partes que conforme a lo establecido en el artículo 39 de la Ley sobre Facultades, Normas y Organización del Indecopi, aprobada por Decreto Legislativo 807, los gastos por los peritajes realizados, actuación de pruebas, inspecciones y otros derivados de la tramitación del proceso serán de cargo de la parte que solicita la prueba, salvo pacto en contrario. En todos los casos, la resolución final determinará si los gastos deben ser asumidos por alguna de las partes, o reembolsados a la otra parte o al Indecopi, según sea el caso, de manera adicional a la sanción que haya podido imponerse.",
    "OCTAVO": "comunicar a las partes que, de acuerdo a lo señalado por el artículo 29 del Decreto Legislativo 807__F11__, hasta antes de la emisión de la Resolución Final tienen la posibilidad de solicitar una audiencia de conciliación. En caso deleguen a favor de una tercera persona su actuación en la diligencia programada, ésta deberá presentar un poder especial con firma legalizada ante Notario Público, donde conste expresamente su facultad para asistir y conciliar en su representación. Ello bajo apercibimiento de no realizar la audiencia de conciliación y levantar el acta de inasistencia correspondiente."
  },
  "footnotes": {
    "__F1__": "Denuncia remitida a esta Comisión mediante DOCUMENTO DE TRASLADO de fecha 16 de junio de 2026.",
    "__F2__": "Publicado el 2 de setiembre del 2010 en el Diario Oficial El Peruano, vigente desde el 2 de octubre del 2010 y modificado por Decreto Legislativo 1308.",
    "__F3__": "LEY 29571, CÓDIGO DE PROTECCIÓN Y DEFENSA DEL CONSUMIDOR, publicado el 2 de setiembre de 2010 y modificado por Decreto Legislativo N 1308\nArtículo 105.- Autoridad competente.\nEl Instituto Nacional de Defensa de la Competencia y de la Protección de la Propiedad Intelectual (Indecopi) es la autoridad con competencia primaria y de alcance nacional para conocer las presuntas infracciones a las disposiciones contenidas en el presente Código, así como para imponer las sanciones y medidas correctivas establecidas en el presente capítulo, conforme al Decreto Legislativo N 1033, Ley de Organización y Funciones del Indecopi. Dicha competencia solo puede ser negada cuando ella haya sido asignada o se asigne a favor de otro organismo por norma expresa con rango de ley.\n(...).\n\nLEY DE ORGANIZACIÓN Y FUNCIONES DEL INDECOPI, APROBADA POR DECRETO LEGISLATIVO N 1033\nArtículo 27.- De la Comisión de Protección al Consumidor.-\nCorresponde a la Comisión de Protección al Consumidor velar por el cumplimiento de la Ley de Protección al Consumidor y de las leyes que, en general, protegen a los consumidores de la falta de idoneidad de los bienes y servicios en función de la información brindada, de las omisiones de información y de la discriminación en el consumo, así como de aquellas que complementen o sustituyan a las anteriores.",
    "__F4__": "LEY 29571, CÓDIGO DE PROTECCIÓN Y DEFENSA DEL CONSUMIDOR, publicado el 2 de setiembre de 2010 y modificado por Decreto Legislativo N 1308\nArtículo 18.- Idoneidad\nSe entiende por idoneidad la correspondencia entre lo que un consumidor espera y lo que efectivamente recibe, en función a lo que se le hubiera ofrecido, la publicidad e información transmitida, las condiciones y circunstancias de la transacción, las características y naturaleza del producto o servicio, el precio, entre otros factores, atendiendo a las circunstancias del caso.\nLa idoneidad es evaluada en función a la propia naturaleza del producto o servicio y a su aptitud para satisfacer la finalidad para la cual ha sido puesto en el mercado. Las autorizaciones por parte de los organismos del Estado para la fabricación de un producto o la prestación de un servicio, en los casos que sea necesario, no eximen de responsabilidad al proveedor frente al consumidor.\n\nArtículo 19.- Obligación de los proveedores\nEl proveedor responde por la idoneidad y calidad de los productos y servicios ofrecidos; por la autenticidad de las marcas y leyendas que exhiben sus productos o del signo que respalda al prestador del servicio, por la falta de conformidad entre la publicidad comercial de los productos y servicios y éstos, así como por el contenido y la vida útil del producto indicado en el envase, en lo que corresponda."
  }
}

with open(Path("casos") / "2222-2026.json", "w", encoding="utf-8") as f:
    json.dump(caso, f, ensure_ascii=False, indent=2)
