name: Generar Resoluciones y Release

on:
  push:
    branches:
      - main

jobs:
  generate-and-release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Habilitar long paths en Git (Windows)
        run: git config --global core.longpaths true

      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar uv (si no está instalado)
        run: |
          if (!(Get-Command uv -ErrorAction SilentlyContinue)) {
            Invoke-WebRequest -Uri https://astral.sh/uv/install.ps1 -OutFile install_uv.ps1
            powershell -ExecutionPolicy ByPass -File install_uv.ps1
          }



      - name: Crear Release de GitHub
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Actualización de Código v1.0.${{ github.run_number }}
          body: Nueva versión del código de automatización desplegada.
